"""location is optional

Revision ID: 23543e8a4ed8
Revises: 2130b60cde2f
Create Date: 2024-03-31 00:19:59.714406

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23543e8a4ed8"
down_revision: Union[str, None] = "2130b60cde2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("hotels", "location", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("hotels", "location", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
