"""del room image_id

Revision ID: 4d843b928465
Revises: 9db87f144afb
Create Date: 2024-03-30 23:06:35.193375

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d843b928465"
down_revision: Union[str, None] = "9db87f144afb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rooms", "image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
