"""add column images

Revision ID: b70b6926f3fa
Revises: 1ab636fa4cc5
Create Date: 2024-03-30 18:54:27.630952

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b70b6926f3fa"
down_revision: Union[str, None] = "1ab636fa4cc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column("image_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
