"""fix hotels min price

Revision ID: c2f6c6785761
Revises: 23543e8a4ed8
Create Date: 2024-03-31 00:22:22.815827

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c2f6c6785761"
down_revision: Union[str, None] = "23543e8a4ed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
