"""change column images

Revision ID: f18718391a84
Revises: b70b6926f3fa
Create Date: 2024-03-30 22:12:32.943495

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f18718391a84"
down_revision: Union[str, None] = "b70b6926f3fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "images")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotels",
        sa.Column(
            "images", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
