"""add hotels column

Revision ID: f906afcb977e
Revises: 73500fbaacd4
Create Date: 2024-03-28 18:57:21.744795

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f906afcb977e"
down_revision: Union[str, None] = "73500fbaacd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("min_price", sa.Float(), nullable=True))
    op.add_column("hotels", sa.Column("coordinates", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "coordinates")
    op.drop_column("hotels", "min_price")
    # ### end Alembic commands ###
